name: Add Rules to Cloudflare Gateway
on:
  push:
  workflow_dispatch:

jobs:
  run:
    name: Cloudflare Gateway
    permissions:
      actions: read
      checks: read
      contents: read
      issues: read
      repository-projects: read
      statuses: read
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
      CF_IDENTIFIER: ${{ secrets.CF_IDENTIFIER }}
      ADLIST_URLS: ${{ vars.ADLIST_URLS }}
      WHITELIST_URLS: ${{ vars.WHITELIST_URLS }}
      DYNAMIC_BLACKLIST: ${{ vars.DYNAMIC_BLACKLIST }}
      DYNAMIC_WHITELIST: ${{ vars.DYNAMIC_WHITELIST }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Verify GitHub CLI
        run: gh --version

      # Kiểm tra trạng thái workflow gần nhất
      - name: Check previous workflow status
        id: check-status
        run: |
          STATUS=$(gh run list --limit 1 --json conclusion -q '.[0].conclusion')
          echo "Previous workflow status: $STATUS"
          echo "STATUS=$STATUS" >> $GITHUB_ENV  # Lưu trạng thái vào Environment Files
          echo "Current STATUS: ${STATUS}"  # In trạng thái để kiểm tra

      # Chỉ sử dụng cache nếu workflow trước đó thành công
      - name: Cache Data
        id: cache-cloudflare-data
        uses: actions/cache@v3
        if: env.STATUS == 'success'  # Sử dụng cache nếu workflow trước đó thành công
        with:
          path: cloudflare_cache.json
          key: ${{ runner.os }}-cloudflare-data
          restore-keys: |
            ${{ runner.os }}-cloudflare-data

      - name: Cloudflare Gateway Zero Trust
        run: python -m src run

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 5  # Giữ lại ít nhất 5 bản chạy trước
