name: Add Rules to Cloudflare Gateway
on:
  push:
  workflow_dispatch:

jobs:
  run:
    name: Cloudflare Gateway
    permissions: write-all
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
      CF_IDENTIFIER: ${{ secrets.CF_IDENTIFIER }}
      ADLIST_URLS: ${{ vars.ADLIST_URLS }}
      WHITELIST_URLS: ${{ vars.WHITELIST_URLS }}
      DYNAMIC_BLACKLIST: ${{ vars.DYNAMIC_BLACKLIST }}
      DYNAMIC_WHITELIST: ${{ vars.DYNAMIC_WHITELIST }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      # Download previous success state artifact
      - name: Download previous success artifact
        id: download-success
        uses: actions/download-artifact@v3
        with:
          name: workflow-success
        continue-on-error: true  # Không báo lỗi nếu không có artifact

      # Use cache only if the previous run was successful
      - name: Cache Data
        id: cache-cloudflare-data
        uses: actions/cache@v3
        if: steps.download-success.outcome == 'success'  # Chỉ sử dụng cache nếu lần chạy trước thành công
        with:
          path: cloudflare_cache.json
          key: ${{ runner.os }}-cloudflare-data-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-cloudflare-data-

      - name: Cloudflare Gateway Zero Trust
        id: cloudflare-run
        run: |
          python -m src run

      # Create a success file to mark this run as successful
      - name: Create success file
        run: echo "success" > dummy_success_file  # Tạo một file giả để lưu trạng thái thành công

      # Upload success state artifact if the workflow run is successful
      - name: Upload success state artifact
        if: success()  # Chỉ upload nếu các bước trước đó thành công
        uses: actions/upload-artifact@v3
        with:
          name: workflow-success
          path: ./dummy_success_file  # Đường dẫn tới file đã tạo

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 1
